fixtures:
  repositories:
    stdlib:
      repo: "--branch #{((ENV['PUPPET_GEM_VERSION'] == '~> 2.6.0' ) ? '2.6.0' : '4.1.0')} git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: ""
  symlinks:
    network: "#{source_dir}"
