fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.24.0'
    ip:
      repo: 'https://github.com/thrnio/puppet-ip.git'
      ref: 'v1.0.0'
  symlinks:
    network: "#{source_dir}"
