#!/bin/bash
RC=0

PROM=$(egrep -i 'promisc' /etc/sysconfig/network-scripts/ifcfg-$1 | awk -F"=" '{ print $2 }' | sed 's/\"//g' )

if [ "$PROM" = "yes" ];
then
/sbin/ifconfig $1 promisc
RC=$?
fi

exit $RC
